%%
% Author:       Sean Tedesco
% Date:         December 31st, 2021
% Description:  Example script of how to write and load an audio file in
%               MATLAB using the built-in chirp.wav file. 
%%

% clean up
clear all; clf

% produce the chirp audio signal
Fs = 5000;                                           % sampling rate
t = 0:1/Fs:5;                                        % time parameter
y0 = 0.1*cos(2*pi*2000*t)-0.8*cos(2*pi*2000*t.^2);    % sinusoid and chirp

% writing chirp.wav file
audiowrite('chirp.wav',y0, Fs)

% reading chirp.wav back into MATLAB as y1 and listening to it
[y1, Fs] = audioread('chirp.wav');
sound(y1, Fs) % sound generated by y1
figure(1)
plot(t(1:1000), y1(1:1000))